title: WingWorks Kiteboarding
author: Karsten Gaebert
email: karsten.gaebert@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Wingworks kiteboarding

sass:
    style: compressed